name: Update IANA Root domains
description: This workflow updates the IANA root domains and runs a Python script to process them.

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-iana-root:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script
        run: python ./src/dnssec.py --source IANA --max 10 --path data

      - name: Update data files
        run: | 
          git status
          git add ./data/*.csv
          git add ./data/*.json
          git -c user.name="GitHub Actions" -c user.email="none@darkpeaklabs.com" commit -m "Updating IANA DNSSEC data"
          git config pull.rebase false
          git pull
          git push        
